"""Add soft delete tombstones

Revision ID: 56f069e8711f
Revises: a38a64aee2cc
Create Date: 2025-05-30 15:48:33.558824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '56f069e8711f'
down_revision: Union[str, None] = 'a38a64aee2cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add soft delete columns to all syncable tables
    op.add_column('audit_logs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('audit_logs', sa.Column('deleted_by', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_index(op.f('ix_audit_logs_deleted_at'), 'audit_logs', ['deleted_at'], unique=False)
    
    op.add_column('parties', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('parties', sa.Column('deleted_by', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_index(op.f('ix_parties_deleted_at'), 'parties', ['deleted_at'], unique=False)
    
    op.add_column('tally_lines', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('tally_lines', sa.Column('deleted_by', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_index(op.f('ix_tally_lines_deleted_at'), 'tally_lines', ['deleted_at'], unique=False)
    
    op.add_column('tally_sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('tally_sessions', sa.Column('deleted_by', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_index(op.f('ix_tally_sessions_deleted_at'), 'tally_sessions', ['deleted_at'], unique=False)
    
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_by', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    
    op.add_column('voters', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('voters', sa.Column('deleted_by', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_index(op.f('ix_voters_deleted_at'), 'voters', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove soft delete columns from all syncable tables
    op.drop_index(op.f('ix_voters_deleted_at'), table_name='voters')
    op.drop_column('voters', 'deleted_by')
    op.drop_column('voters', 'deleted_at')
    
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'deleted_at')
    
    op.drop_index(op.f('ix_tally_sessions_deleted_at'), table_name='tally_sessions')
    op.drop_column('tally_sessions', 'deleted_by')
    op.drop_column('tally_sessions', 'deleted_at')
    
    op.drop_index(op.f('ix_tally_lines_deleted_at'), table_name='tally_lines')
    op.drop_column('tally_lines', 'deleted_by')
    op.drop_column('tally_lines', 'deleted_at')
    
    op.drop_index(op.f('ix_parties_deleted_at'), table_name='parties')
    op.drop_column('parties', 'deleted_by')
    op.drop_column('parties', 'deleted_at')
    
    op.drop_index(op.f('ix_audit_logs_deleted_at'), table_name='audit_logs')
    op.drop_column('audit_logs', 'deleted_by')
    op.drop_column('audit_logs', 'deleted_at')
    # ### end Alembic commands ###
